title:            eLitmus Blog
description:      We learn new things everyday, and we document our learnings here...
logo:             blog_logo_taglinedorange.png
disqus_shortname:
search:           true
# Change url to your domain. Leave localhost server or blank when working locally.
# You don't need to specify the protocol if you want it available on http and https. Example: //localhost:4000
# url:              //lvh.me:4000
url:              ""
baseurl:          /blog
url_for_sitemaps: https://www.elitmus.com
canonical_domain: ""
# Owner/author information
owner:
  name:           eLitmus.com
  avatar:         bio-photo.jpg
  email:          site-admin@elitmus.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: elitmus
  facebook: elitmusnow
  github:
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus: https://plus.google.com/+eLitmus


# Analytics and webmaster tools stuff goes here
google_analytics: 'UA-707704-1'
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    icon: "fa fa-home"
  - title: Posts
    url: /posts/
    icon: "fa fa-file-text-o"
  - title: eLitmus
    url: //www.elitmus.com/
    external: true
    icon: "el el-elitmuslogo"

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: pygments
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  

  syntax_highlighter_opts:
    line_numbers:
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["server.sh","lib", "config.rb", "Gemfile", "Capfile", "README.md", "LICENSE", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: []
show_job: true
